//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure", IsNullable = false)]
public partial class DungeonData
{

    private string introField;

    private cantTakeItWithYouType cantTakeItWithYouField;

    private roomType[] roomListField;

    private MonsterType[] monsterListField;

    private itemType[] itemListField;

    /// <remarks/>
    public string Intro
    {
        get
        {
            return this.introField;
        }
        set
        {
            this.introField = value;
        }
    }

    /// <remarks/>
    public cantTakeItWithYouType CantTakeItWithYou
    {
        get
        {
            return this.cantTakeItWithYouField;
        }
        set
        {
            this.cantTakeItWithYouField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Room", IsNullable = false)]
    public roomType[] RoomList
    {
        get
        {
            return this.roomListField;
        }
        set
        {
            this.roomListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Monster", IsNullable = false)]
    public MonsterType[] MonsterList
    {
        get
        {
            return this.monsterListField;
        }
        set
        {
            this.monsterListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
    public itemType[] ItemList
    {
        get
        {
            return this.itemListField;
        }
        set
        {
            this.itemListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class cantTakeItWithYouType
{

    private int startingArmorClassField;

    private int[] startingItemField;

    /// <remarks/>
    public int StartingArmorClass
    {
        get
        {
            return this.startingArmorClassField;
        }
        set
        {
            this.startingArmorClassField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StartingItem")]
    public int[] StartingItem
    {
        get
        {
            return this.startingItemField;
        }
        set
        {
            this.startingItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class elementItemTriggerNameType
{

    private string argField;

    private itemTriggerNameType valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string arg
    {
        get
        {
            return this.argField;
        }
        set
        {
            this.argField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public itemTriggerNameType Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public enum itemTriggerNameType
{

    /// <remarks/>
    OnBlast,

    /// <remarks/>
    OnDrink,

    /// <remarks/>
    OnExamine,

    /// <remarks/>
    OnGet,

    /// <remarks/>
    OnDrop,

    /// <remarks/>
    OnMagicWord,

    /// <remarks/>
    OnPower,

    /// <remarks/>
    OnRead,

    /// <remarks/>
    OnUse,

    /// <remarks/>
    OnOpen,

    /// <remarks/>
    OnClose,

    /// <remarks/>
    OnWear,

    /// <remarks/>
    OnRemove,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class itemTriggerType
{

    private elementItemTriggerNameType triggerField;

    private actionType[] actionField;

    /// <remarks/>
    public elementItemTriggerNameType trigger
    {
        get
        {
            return this.triggerField;
        }
        set
        {
            this.triggerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action")]
    public actionType[] action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(wakeCreatureAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(toggleAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(setTimerAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(setConstantAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(showTextAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(revealItemAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(revealExitAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(readyWeaponAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(permaBoostPlayerStatAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(modifyWeaponAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(openStorageAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hideExitAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(healPlayerAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(goToRoomAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(executeIfAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(doorLockAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(destroyItemAction))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public abstract partial class actionType
{

    private string textField;

    /// <remarks/>
    public string text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class wakeCreatureAction : actionType
{

    private int monsterIdField;

    private string roomIdField;

    /// <remarks/>
    public int monsterId
    {
        get
        {
            return this.monsterIdField;
        }
        set
        {
            this.monsterIdField = value;
        }
    }

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class toggleAction : actionType
{

    private actionType[] actionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action")]
    public actionType[] action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class setTimerAction : actionType
{

    private string nameField;

    private int durationField;

    private bool repeatField;

    private actionType[] actionField;

    public setTimerAction()
    {
        this.repeatField = false;
    }

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public int duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool repeat
    {
        get
        {
            return this.repeatField;
        }
        set
        {
            this.repeatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action")]
    public actionType[] action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class setConstantAction : actionType
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class showTextAction : actionType
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class revealItemAction : actionType
{

    private int itemIdField;

    private string roomIdField;

    /// <remarks/>
    public int itemId
    {
        get
        {
            return this.itemIdField;
        }
        set
        {
            this.itemIdField = value;
        }
    }

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class revealExitAction : actionType
{

    private directionType directionField;

    private string roomIdField;

    /// <remarks/>
    public directionType direction
    {
        get
        {
            return this.directionField;
        }
        set
        {
            this.directionField = value;
        }
    }

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public enum directionType
{

    /// <remarks/>
    n,

    /// <remarks/>
    s,

    /// <remarks/>
    e,

    /// <remarks/>
    w,

    /// <remarks/>
    ne,

    /// <remarks/>
    se,

    /// <remarks/>
    nw,

    /// <remarks/>
    sw,

    /// <remarks/>
    u,

    /// <remarks/>
    d,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class readyWeaponAction : actionType
{

    private int weaponItemIdField;

    /// <remarks/>
    public int weaponItemId
    {
        get
        {
            return this.weaponItemIdField;
        }
        set
        {
            this.weaponItemIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class permaBoostPlayerStatAction : actionType
{

    private string statField;

    private int valueField;

    /// <remarks/>
    public string stat
    {
        get
        {
            return this.statField;
        }
        set
        {
            this.statField = value;
        }
    }

    /// <remarks/>
    public int value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class modifyWeaponAction : actionType
{

    private int idField;

    private diceType damageField;

    private string descriptionField;

    /// <remarks/>
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public diceType damage
    {
        get
        {
            return this.damageField;
        }
        set
        {
            this.damageField = value;
        }
    }

    /// <remarks/>
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class diceType
{

    private int sidesField;

    private int countField;

    private int plusField;

    /// <remarks/>
    public int Sides
    {
        get
        {
            return this.sidesField;
        }
        set
        {
            this.sidesField = value;
        }
    }

    /// <remarks/>
    public int Count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }

    /// <remarks/>
    public int Plus
    {
        get
        {
            return this.plusField;
        }
        set
        {
            this.plusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class openStorageAction : actionType
{

    private int storageItemIdField;

    /// <remarks/>
    public int storageItemId
    {
        get
        {
            return this.storageItemIdField;
        }
        set
        {
            this.storageItemIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class hideExitAction : actionType
{

    private directionType directionField;

    private string roomIdField;

    /// <remarks/>
    public directionType direction
    {
        get
        {
            return this.directionField;
        }
        set
        {
            this.directionField = value;
        }
    }

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class healPlayerAction : actionType
{

    private int rangeLowField;

    private int rangeHighField;

    /// <remarks/>
    public int rangeLow
    {
        get
        {
            return this.rangeLowField;
        }
        set
        {
            this.rangeLowField = value;
        }
    }

    /// <remarks/>
    public int rangeHigh
    {
        get
        {
            return this.rangeHighField;
        }
        set
        {
            this.rangeHighField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class goToRoomAction : actionType
{

    private string roomIdField;

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class executeIfAction : actionType
{

    private conditionType conditionField;

    private actionType[] actionField;

    private actionType[] elseActionField;

    /// <remarks/>
    public conditionType condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action")]
    public actionType[] action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("elseAction")]
    public actionType[] elseAction
    {
        get
        {
            return this.elseActionField;
        }
        set
        {
            this.elseActionField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(constantEqualsCondition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(playerHoldingItemCondition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(playerInRoomCondition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(monsterInRoomCondition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(itemInRoomCondition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(notCondition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(orCondition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(andCondition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public abstract partial class conditionType
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class constantEqualsCondition : conditionType
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class playerHoldingItemCondition : conditionType
{

    private int itemIdField;

    /// <remarks/>
    public int itemId
    {
        get
        {
            return this.itemIdField;
        }
        set
        {
            this.itemIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class playerInRoomCondition : conditionType
{

    private string roomIdField;

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class monsterInRoomCondition : conditionType
{

    private int monsterIdField;

    private string roomIdField;

    /// <remarks/>
    public int monsterId
    {
        get
        {
            return this.monsterIdField;
        }
        set
        {
            this.monsterIdField = value;
        }
    }

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class itemInRoomCondition : conditionType
{

    private int itemIdField;

    private string roomIdField;

    /// <remarks/>
    public int itemId
    {
        get
        {
            return this.itemIdField;
        }
        set
        {
            this.itemIdField = value;
        }
    }

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class notCondition : conditionType
{

    private conditionType conditionField;

    /// <remarks/>
    public conditionType condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class orCondition : conditionType
{

    private conditionType[] conditionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("condition")]
    public conditionType[] condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class andCondition : conditionType
{

    private conditionType[] conditionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("condition")]
    public conditionType[] condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class doorLockAction : actionType
{

    private directionType directionField;

    private string roomIdField;

    private bool lockItField;

    /// <remarks/>
    public directionType direction
    {
        get
        {
            return this.directionField;
        }
        set
        {
            this.directionField = value;
        }
    }

    /// <remarks/>
    public string roomId
    {
        get
        {
            return this.roomIdField;
        }
        set
        {
            this.roomIdField = value;
        }
    }

    /// <remarks/>
    public bool lockIt
    {
        get
        {
            return this.lockItField;
        }
        set
        {
            this.lockItField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class destroyItemAction : actionType
{

    private int idField;

    /// <remarks/>
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class storageType
{

    private bool isOpenField;

    private bool closableField;

    private bool openableField;

    private string cantOpenPhraseField;

    private int maxWeightField;

    private int[] contentsField;

    public storageType()
    {
        this.isOpenField = true;
        this.closableField = false;
        this.openableField = false;
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool isOpen
    {
        get
        {
            return this.isOpenField;
        }
        set
        {
            this.isOpenField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool closable
    {
        get
        {
            return this.closableField;
        }
        set
        {
            this.closableField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool openable
    {
        get
        {
            return this.openableField;
        }
        set
        {
            this.openableField = value;
        }
    }

    /// <remarks/>
    public string CantOpenPhrase
    {
        get
        {
            return this.cantOpenPhraseField;
        }
        set
        {
            this.cantOpenPhraseField = value;
        }
    }

    /// <remarks/>
    public int maxWeight
    {
        get
        {
            return this.maxWeightField;
        }
        set
        {
            this.maxWeightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Contents")]
    public int[] Contents
    {
        get
        {
            return this.contentsField;
        }
        set
        {
            this.contentsField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(weaponData))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class itemType
{

    private int idField;

    private string nameField;

    private string descriptionField;

    private int baseValueField;

    private int weightField;

    private bool canLightField;

    private bool isMoneyField;

    private storageType storageField;

    private bool revealedField;

    private bool isWearableField;

    private bool isArmorField;

    private int armorClassField;

    private itemTriggerType[] triggerField;

    public itemType()
    {
        this.canLightField = false;
        this.isMoneyField = false;
        this.revealedField = true;
        this.isWearableField = false;
        this.isArmorField = false;
        this.armorClassField = 0;
    }

    /// <remarks/>
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public int baseValue
    {
        get
        {
            return this.baseValueField;
        }
        set
        {
            this.baseValueField = value;
        }
    }

    /// <remarks/>
    public int weight
    {
        get
        {
            return this.weightField;
        }
        set
        {
            this.weightField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool canLight
    {
        get
        {
            return this.canLightField;
        }
        set
        {
            this.canLightField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isMoney
    {
        get
        {
            return this.isMoneyField;
        }
        set
        {
            this.isMoneyField = value;
        }
    }

    /// <remarks/>
    public storageType storage
    {
        get
        {
            return this.storageField;
        }
        set
        {
            this.storageField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool revealed
    {
        get
        {
            return this.revealedField;
        }
        set
        {
            this.revealedField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isWearable
    {
        get
        {
            return this.isWearableField;
        }
        set
        {
            this.isWearableField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isArmor
    {
        get
        {
            return this.isArmorField;
        }
        set
        {
            this.isArmorField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int armorClass
    {
        get
        {
            return this.armorClassField;
        }
        set
        {
            this.armorClassField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trigger")]
    public itemTriggerType[] Trigger
    {
        get
        {
            return this.triggerField;
        }
        set
        {
            this.triggerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class weaponData : itemType
{

    private WeaponAttackType attackField;

    /// <remarks/>
    public WeaponAttackType Attack
    {
        get
        {
            return this.attackField;
        }
        set
        {
            this.attackField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class WeaponAttackType : AttackType
{

    private weaponType typeField;

    private int complexityField;

    /// <remarks/>
    public weaponType Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public int Complexity
    {
        get
        {
            return this.complexityField;
        }
        set
        {
            this.complexityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public enum weaponType
{

    /// <remarks/>
    Axe,

    /// <remarks/>
    Bow,

    /// <remarks/>
    Mace,

    /// <remarks/>
    Spear,

    /// <remarks/>
    Sword,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeaponAttackType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class AttackType
{

    private diceType attackDiceField;

    private string[] attackPhrasesField;

    /// <remarks/>
    public diceType AttackDice
    {
        get
        {
            return this.attackDiceField;
        }
        set
        {
            this.attackDiceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Phrase", IsNullable = false)]
    public string[] AttackPhrases
    {
        get
        {
            return this.attackPhrasesField;
        }
        set
        {
            this.attackPhrasesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class AutoCorpseType
{

    private string descriptionField;

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class elementMonsterTriggerNameType
{

    private string argField;

    private monsterTriggerNameType valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string arg
    {
        get
        {
            return this.argField;
        }
        set
        {
            this.argField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public monsterTriggerNameType Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public enum monsterTriggerNameType
{

    /// <remarks/>
    OnBlast,

    /// <remarks/>
    OnKill,

    /// <remarks/>
    OnMagicWord,

    /// <remarks/>
    OnPower,

    /// <remarks/>
    OnWound,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class monsterTriggerType
{

    private elementMonsterTriggerNameType triggerField;

    private actionType[] actionField;

    /// <remarks/>
    public elementMonsterTriggerNameType trigger
    {
        get
        {
            return this.triggerField;
        }
        set
        {
            this.triggerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action")]
    public actionType[] action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CharacterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MonsterType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class CreatureType
{

    private int idField;

    private string nameField;

    private int hardinessField;

    private int agilityField;

    private int armorClassField;

    private CreatureTypeItems itemsField;

    /// <remarks/>
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public int Hardiness
    {
        get
        {
            return this.hardinessField;
        }
        set
        {
            this.hardinessField = value;
        }
    }

    /// <remarks/>
    public int Agility
    {
        get
        {
            return this.agilityField;
        }
        set
        {
            this.agilityField = value;
        }
    }

    /// <remarks/>
    public int ArmorClass
    {
        get
        {
            return this.armorClassField;
        }
        set
        {
            this.armorClassField = value;
        }
    }

    /// <remarks/>
    public CreatureTypeItems Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class CreatureTypeItems
{

    private int[] itemField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public int[] Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class CharacterType : CreatureType
{

    private byte armorExpertiseField;

    private sbyte axeField;

    private sbyte bowField;

    private sbyte maceField;

    private sbyte spearField;

    private sbyte swordField;

    private sbyte charismaField;

    private sbyte healField;

    private sbyte blastField;

    private sbyte powerField;

    private sbyte speedField;

    private ulong goldField;

    private ulong goldInBankField;

    private weaponData[] weaponListField;

    /// <remarks/>
    public byte ArmorExpertise
    {
        get
        {
            return this.armorExpertiseField;
        }
        set
        {
            this.armorExpertiseField = value;
        }
    }

    /// <remarks/>
    public sbyte Axe
    {
        get
        {
            return this.axeField;
        }
        set
        {
            this.axeField = value;
        }
    }

    /// <remarks/>
    public sbyte Bow
    {
        get
        {
            return this.bowField;
        }
        set
        {
            this.bowField = value;
        }
    }

    /// <remarks/>
    public sbyte Mace
    {
        get
        {
            return this.maceField;
        }
        set
        {
            this.maceField = value;
        }
    }

    /// <remarks/>
    public sbyte Spear
    {
        get
        {
            return this.spearField;
        }
        set
        {
            this.spearField = value;
        }
    }

    /// <remarks/>
    public sbyte Sword
    {
        get
        {
            return this.swordField;
        }
        set
        {
            this.swordField = value;
        }
    }

    /// <remarks/>
    public sbyte Charisma
    {
        get
        {
            return this.charismaField;
        }
        set
        {
            this.charismaField = value;
        }
    }

    /// <remarks/>
    public sbyte Heal
    {
        get
        {
            return this.healField;
        }
        set
        {
            this.healField = value;
        }
    }

    /// <remarks/>
    public sbyte Blast
    {
        get
        {
            return this.blastField;
        }
        set
        {
            this.blastField = value;
        }
    }

    /// <remarks/>
    public sbyte Power
    {
        get
        {
            return this.powerField;
        }
        set
        {
            this.powerField = value;
        }
    }

    /// <remarks/>
    public sbyte Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    public ulong Gold
    {
        get
        {
            return this.goldField;
        }
        set
        {
            this.goldField = value;
        }
    }

    /// <remarks/>
    public ulong GoldInBank
    {
        get
        {
            return this.goldInBankField;
        }
        set
        {
            this.goldInBankField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Weapon", IsNullable = false)]
    public weaponData[] WeaponList
    {
        get
        {
            return this.weaponListField;
        }
        set
        {
            this.weaponListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class MonsterType : CreatureType
{

    private AttackType naturalAttackField;

    private string descriptionField;

    private DispositionType dispositionField;

    private int friendlinessField;

    private bool friendlinessFieldSpecified;

    private int courageField;

    private bool noFollowField;

    private bool canUseWeaponsField;

    private weaponType[] canUseWeaponTypesField;

    private int favoredWeaponIDField;

    private bool favoredWeaponIDFieldSpecified;

    private int weaponIDField;

    private bool weaponIDFieldSpecified;

    private monsterTriggerType[] triggerField;

    private AutoCorpseType autoCorpseField;

    public MonsterType()
    {
        this.noFollowField = false;
    }

    /// <remarks/>
    public AttackType NaturalAttack
    {
        get
        {
            return this.naturalAttackField;
        }
        set
        {
            this.naturalAttackField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public DispositionType Disposition
    {
        get
        {
            return this.dispositionField;
        }
        set
        {
            this.dispositionField = value;
        }
    }

    /// <remarks/>
    public int Friendliness
    {
        get
        {
            return this.friendlinessField;
        }
        set
        {
            this.friendlinessField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FriendlinessSpecified
    {
        get
        {
            return this.friendlinessFieldSpecified;
        }
        set
        {
            this.friendlinessFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int Courage
    {
        get
        {
            return this.courageField;
        }
        set
        {
            this.courageField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool NoFollow
    {
        get
        {
            return this.noFollowField;
        }
        set
        {
            this.noFollowField = value;
        }
    }

    /// <remarks/>
    public bool CanUseWeapons
    {
        get
        {
            return this.canUseWeaponsField;
        }
        set
        {
            this.canUseWeaponsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WeaponType", IsNullable = false)]
    public weaponType[] CanUseWeaponTypes
    {
        get
        {
            return this.canUseWeaponTypesField;
        }
        set
        {
            this.canUseWeaponTypesField = value;
        }
    }

    /// <remarks/>
    public int FavoredWeaponID
    {
        get
        {
            return this.favoredWeaponIDField;
        }
        set
        {
            this.favoredWeaponIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FavoredWeaponIDSpecified
    {
        get
        {
            return this.favoredWeaponIDFieldSpecified;
        }
        set
        {
            this.favoredWeaponIDFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int WeaponID
    {
        get
        {
            return this.weaponIDField;
        }
        set
        {
            this.weaponIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WeaponIDSpecified
    {
        get
        {
            return this.weaponIDFieldSpecified;
        }
        set
        {
            this.weaponIDFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trigger")]
    public monsterTriggerType[] Trigger
    {
        get
        {
            return this.triggerField;
        }
        set
        {
            this.triggerField = value;
        }
    }

    /// <remarks/>
    public AutoCorpseType AutoCorpse
    {
        get
        {
            return this.autoCorpseField;
        }
        set
        {
            this.autoCorpseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public enum DispositionType
{

    /// <remarks/>
    Angry,

    /// <remarks/>
    Friendly,

    /// <remarks/>
    Neutral,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(lockableDoorType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class doorType
{

    private directionType directionField;

    private string roomNameField;

    private bool toMainHallField;

    private bool visibleField;

    public doorType()
    {
        this.toMainHallField = false;
        this.visibleField = true;
    }

    /// <remarks/>
    public directionType direction
    {
        get
        {
            return this.directionField;
        }
        set
        {
            this.directionField = value;
        }
    }

    /// <remarks/>
    public string roomName
    {
        get
        {
            return this.roomNameField;
        }
        set
        {
            this.roomNameField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool toMainHall
    {
        get
        {
            return this.toMainHallField;
        }
        set
        {
            this.toMainHallField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool visible
    {
        get
        {
            return this.visibleField;
        }
        set
        {
            this.visibleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class lockableDoorType : doorType
{

    private bool lockedField;

    private string lockedDescriptionField;

    private string unlockedDescriptionField;

    private string unlockPhraseField;

    private string lockPhraseField;

    private string keyItemIdField;

    private string keyItemActionField;

    /// <remarks/>
    public bool locked
    {
        get
        {
            return this.lockedField;
        }
        set
        {
            this.lockedField = value;
        }
    }

    /// <remarks/>
    public string LockedDescription
    {
        get
        {
            return this.lockedDescriptionField;
        }
        set
        {
            this.lockedDescriptionField = value;
        }
    }

    /// <remarks/>
    public string UnlockedDescription
    {
        get
        {
            return this.unlockedDescriptionField;
        }
        set
        {
            this.unlockedDescriptionField = value;
        }
    }

    /// <remarks/>
    public string UnlockPhrase
    {
        get
        {
            return this.unlockPhraseField;
        }
        set
        {
            this.unlockPhraseField = value;
        }
    }

    /// <remarks/>
    public string LockPhrase
    {
        get
        {
            return this.lockPhraseField;
        }
        set
        {
            this.lockPhraseField = value;
        }
    }

    /// <remarks/>
    public string keyItemId
    {
        get
        {
            return this.keyItemIdField;
        }
        set
        {
            this.keyItemIdField = value;
        }
    }

    /// <remarks/>
    public string keyItemAction
    {
        get
        {
            return this.keyItemActionField;
        }
        set
        {
            this.keyItemActionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class elementRoomTriggerNameType
{

    private string argField;

    private roomTriggerNameType valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string arg
    {
        get
        {
            return this.argField;
        }
        set
        {
            this.argField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public roomTriggerNameType Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public enum roomTriggerNameType
{

    /// <remarks/>
    OnFirstEnter,

    /// <remarks/>
    OnEachEnter,

    /// <remarks/>
    OnExamine,

    /// <remarks/>
    OnMagicWord,

    /// <remarks/>
    OnPower,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class roomTriggerType
{

    private elementRoomTriggerNameType triggerField;

    private actionType[] actionField;

    /// <remarks/>
    public elementRoomTriggerNameType trigger
    {
        get
        {
            return this.triggerField;
        }
        set
        {
            this.triggerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action")]
    public actionType[] action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
public partial class roomType
{

    private string nameField;

    private string titleField;

    private string descriptionField;

    private string shortDescriptionField;

    private bool lightField;

    private roomTriggerType[] triggerField;

    private doorType[] exitsField;

    private int[] creaturesField;

    private int[] itemsField;

    public roomType()
    {
        this.lightField = true;
    }

    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string ShortDescription
    {
        get
        {
            return this.shortDescriptionField;
        }
        set
        {
            this.shortDescriptionField = value;
        }
    }

    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool Light
    {
        get
        {
            return this.lightField;
        }
        set
        {
            this.lightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trigger")]
    public roomTriggerType[] Trigger
    {
        get
        {
            return this.triggerField;
        }
        set
        {
            this.triggerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Exit", IsNullable = false)]
    public doorType[] Exits
    {
        get
        {
            return this.exitsField;
        }
        set
        {
            this.exitsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CreatureID", IsNullable = false)]
    public int[] Creatures
    {
        get
        {
            return this.creaturesField;
        }
        set
        {
            this.creaturesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
    public int[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/Adventure")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Adventure", IsNullable = false)]
public partial class CharacterList
{

    private CharacterType[] characterField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Character")]
    public CharacterType[] Character
    {
        get
        {
            return this.characterField;
        }
        set
        {
            this.characterField = value;
        }
    }
}
